### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './output/NN_with_series_feature/fold0.ckpt'

### ISSUE THREAD

**Issue by sunalawa** [jxzly/Kaggle-American-Express-Default-Prediction-1st-solution#3]
Hi,
I am trying out this project on a AWS instance.
I have completed steps S1 - S5 without any errors or warnings.
But with the file S6_NN_main.py I get a file not found error as follows.
![image](https://github.com/jxzly/Kaggle-American-Express-Default-Prediction-1st-solution/assets/81951809/db5a4b70-8841-4302-8564-5b237eaf5508)

`Traceback (most recent call last):
  File "/home/ubuntu/final-year-easy/S6_NN_main.py", line 41, in <module>
    NN_train_and_predict([df,f,y,series_idx.values[:y.shape[0]]],[df,f,series_idx.values[y.shape[0]:]],Amodel,nn_config,use_series_oof=False,run_id='NN_with_series_feature')
  File "/home/ubuntu/final-year-easy/utils.py", line 409, in NN_train_and_predict
    state_dict = torch.load(output_path + 'fold%s.ckpt'%fold, torch.device('cuda' if torch.cuda.is_available() else 'cpu') )
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './output/NN_with_series_feature/fold0.ckpt'`

I haven't changed anything other than the "folds = 5" to "folds = 3" value in nn_config.

I have a Tesla T4 GPU with CUDA enabled

**Comment by jxzly** [comment]
Do you run 
`NN_train_and_predict([df,f,y,series_idx.values[:y.shape[0]]],[df,f,series_idx.values[y.shape[0]:]],Amodel,nn_config,use_series_oof=False,run_id='NN_with_series_feature')`
successfully in S6_NN_main.py ?  

It looks like there are some issues here, can you take a look and see what they are?

**Comment by sunalawa** [comment]
The error is at the line you have highlighted. The code stops at line 41.
I not able to understand why the code looks for a .ckpt file before training the neural network.

**Comment by jxzly** [comment]
This step is for pre-training, which is used for feature generation in next step. Can you investigate why this step failed when you ran it?

**Comment by sunalawa** [comment]
I figured out the issue.
I was actually running each file separately. I checked out the run.sh file and found the command is different. The model now trains perfectly. Thanks for the help...  :)

**Comment by sunalawa** [comment]
`Traceback (most recent call last):
  File "/home/ubuntu/final-year-easy/S6_NN_main.py", line 43, in <module>
    NN_train_and_predict([df,f,y,series_idx.values[:y.shape[0]]],[df,f,series_idx.values[y.shape[0]:]],Amodel,nn_config,use_series_oof=True,run_id='NN_with_series_and_all_feature')
  File "/home/ubuntu/final-year-easy/utils.py", line 363, in NN_train_and_predict
    outputs = model(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/final-year-easy/model.py", line 67, in forward
    x2 = self.input_feature_block(data['batch_feature'])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x12758 and 12776x128)`



I got this error after completing the pre-training for run_id='NN_with_series_feature'

**Comment by jxzly** [comment]
It seems that the generated feature dimensions are incorrect. It may be necessary to rerun the entire process.
